### PR TITLE
IKS Upgrade to 1.18

### PR DESCRIPTION
**Pull request by nithyaramakrishnan**
Hi @smguilia 

I have added a section on how to upgrade IBM Data Shield cluster to IKS 1.18. Please let me know if you have any questions.

Thanks,
Nithya

### CODE REVIEW

**Comment by smguilia** [comment]
@nithyaramakrishnan This update seems to already be documented. Can you tell me why its different from the section above it?

**Comment by nithyaramakrishnan** [comment]
Hi @smguilia, the section documented earlier is about how to upgrade Data Shield to Ubuntu 8.04, while this new section is about how to upgrade Data Shield cluster to IKS to 1.18.

**Comment by nithyaramakrishnan** [comment]
Hi @smguilia , 
I noticed that the section for "Upgrading IBM cluster from IKS 1.16 to 1.18 is not added to the IBM official documentation yet. We added a couple more steps to the existing procedure and I have saved the same in the "update.md" file and created a new commit. Please let me know when this will be published and if you have any questions.

Thanks,
Nithya

**Comment by smguilia** [comment]
Hi @nithyaramakrishnan,

@ccbarragan has an issue in her sprint this week to look into this. We still have a few open questions about how these instructions are different from upgrading data shield or why we wouldn't link over to the IKS docs instead. She will post here when the changes are merged so that you can take a look and let us know what you think.

-Shawna

**Comment by smguilia** [comment]
Closing this PR as this change will not be part of the next release.

Going to open an internal issue so that when it is we can update the documentation.

Thanks Nithya!

**Pull request closed without merging**
